logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.quartz: DEBUG

server:
  port: 8080
spring:
  messages:
    basename: messages/messages
  profiles:
    active:
      - h2
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always

