CREATE TABLE vets
(
    id         integer generated by default as identity,
    first_name VARCHAR(30),
    last_name  VARCHAR(30),
    PRIMARY KEY (id)
);
CREATE INDEX vets_last_name ON vets (last_name);

CREATE TABLE specialties
(
    id   integer generated by default as identity,
    name VARCHAR(80),
    PRIMARY KEY (id)
);
CREATE INDEX specialties_name ON specialties (name);

CREATE TABLE vet_specialties
(
    vet_id       INTEGER NOT NULL,
    specialty_id INTEGER NOT NULL
);
ALTER TABLE vet_specialties
    ADD CONSTRAINT fk_vet_specialties_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
ALTER TABLE vet_specialties
    ADD CONSTRAINT fk_vet_specialties_specialties FOREIGN KEY (specialty_id) REFERENCES specialties (id);

create table types
(
    id   integer generated by default as identity,
    name varchar(255),
    primary key (id)
);

CREATE TABLE owners
(
    id         integer generated by default as identity,
    first_name VARCHAR(30),
    last_name  VARCHAR_IGNORECASE(30),
    address    VARCHAR(255),
    city       VARCHAR(80),
    telephone  VARCHAR(20),
    PRIMARY KEY (id)
);
CREATE INDEX owners_last_name ON owners (last_name);

CREATE TABLE pets
(
    id         integer generated by default as identity,
    name       VARCHAR(30),
    birth_date DATE,
    type_id    INTEGER NOT NULL,
    owner_id   INTEGER NOT NULL,
    PRIMARY KEY (id)
);
ALTER TABLE pets
    ADD CONSTRAINT fk_pets_owners FOREIGN KEY (owner_id) REFERENCES owners (id);
ALTER TABLE pets
    ADD CONSTRAINT fk_pets_types FOREIGN KEY (type_id) REFERENCES types (id);
CREATE INDEX pets_name ON pets (name);

CREATE TABLE visits
(
    id          integer generated by default as identity,
    pet_id      INTEGER NOT NULL,
    visit_date  DATE,
    description VARCHAR(255),
    PRIMARY KEY (id)
);
ALTER TABLE visits
    ADD CONSTRAINT fk_visits_pets FOREIGN KEY (pet_id) REFERENCES pets (id);
CREATE INDEX visits_pet_id ON visits (pet_id);

CREATE TABLE users
(
    username VARCHAR(20)          NOT NULL,
    password VARCHAR(20)          NOT NULL,
    enabled  BOOLEAN DEFAULT TRUE NOT NULL,
    PRIMARY KEY (username)
);

CREATE TABLE roles
(
    id       integer generated by default as identity,
    username VARCHAR(20) NOT NULL,
    role     VARCHAR(20) NOT NULL,
    PRIMARY KEY (id)
);
ALTER TABLE roles
    ADD CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES users (username);
ALTER TABLE roles
    ADD CONSTRAINT uni_username_role UNIQUE (username, role);
CREATE INDEX fk_username_idx ON roles (username);

